### ISSUE TITLE
get rid of get_global_connection

### ISSUE THREAD

**Issue by ewjoachim** [peopledoc/cabbage#11]
- Link the connection object to the TaskManager,
- Make the TaskManager extensible (inheritance or, preferably, composition) so that someone could implement their own method of connecting to the DB (maybe from Django), with a default implementation that would take no argument and read from env vars, like currently
- Standardize whether functions receive the task manager, the connection or the cursor as parameter. Find the right one and use it consistently where applicable.
- Use consistent connection options and cursor classes.

**Comment by sdispater** [comment]
I am willing to give it a shot :-)

**Comment by ewjoachim** [comment]
Nice ! No idea why, but I can't assign it to you. Feel free to do it :)

**Comment by sdispater** [comment]
I can't assign it to myself either :-(
