### ISSUE TITLE
Rename a few things

### ISSUE THREAD

**Issue by ewjoachim** [peopledoc/cabbage#12]
curs -> cursor
conn -> connection
task_worker.py -> worker.py
worker() -> run_worker() (or something else ?)
task run -> job

**Comment by ewjoachim** [comment]
@nadege have you checked @sdispater 's PR #13 ? And likewise ? It seems you might be doing kind of the same work in parallel :/

**Comment by nadege** [comment]
Hi, yes I did :) So I started my branch from his. But I didn't get the time to actually do some work yet anyway.

**Comment by ewjoachim** [comment]
:+1: The branch is now merged, so you're good to go.

That being said, it looks like the 2 only relevant things left are:
- task_worker.py -> worker.py
- task run -> job

**Comment by ewjoachim** [comment]
So things continue to move around. Now the task run is no more, but might be reintroduced later (probably as "job")

I think the only thing left is renaming "task_worker.py" into "worker.py" and... As much as I'd love to include your contributions, I'm not sure this is worth a ticket anymore.

Let us know what you plan to do :)

That being said, #19 makes a trivial modification in this file and no other PR touches it, so it's not a bad time to make the move.

**Comment by ewjoachim** [comment]
Ah, we could also rename the SQL table "tasks" into "jobs".

**Comment by ewjoachim** [comment]
"targeted_object" could be renamed "lock" to stay consistent with the rest of the codebase.

**Comment by nadege** [comment]
I did not had the time to work on this and I'll not have more soon, I'll unassign myself

**Comment by ewjoachim** [comment]
Thank you, that being said, you're very welcome to join the project later :)
