### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by ewjoachim** [peopledoc/cabbage#4]
For maximum logging extensibility and effectiveness, here's what we could do:

- Every message is bundled with all the context we can think of as `extras`, including a unique code for this log message (e.g. `"action": "start_job"`)
- All logs have a simple associated message, that's "good enough" for the job, without being too much
- All loggers defined directly as `logging.getLogger("cabbage")`
- And we should document how one could implement a log filter, and plug it on cabbage to:
  - Change the log level if they want
  - Change the associated message if they want, including using template variables (loaded from extras)
  - Delete a specific message
  - Implement a specific handler so that these logs are actually not sent to normal logging but, say, written to a file (and then disable bubbling)
  - ...

This way, cabbage logs may be adapted to anyone's need.

**Comment by mgu** [comment]
I prefer `logging.getLogger(__name__)` instead of `logging.getLogger("cabbage")`

**Comment by ewjoachim** [comment]
What wasn't done in #17 will be done in #10
