### ISSUE TITLE
Interrupt the "select" call on signal handle

### ISSUE THREAD

**Issue by ewjoachim** [peopledoc/cabbage#41]
The idea is to register a pipe, then in the select call in postgres.py, listen to the pipe too, and in the signal handler, write in this pipe. This way, we'd leave immediately without waiting for the timeout.

I know we can't do everything in a signal handler, but if we can write to a pipe, then it may help us to stop faster (and make the "timeout" argument really much less important).

https://stackoverflow.com/a/4661284

**Comment by mgu** [comment]
I don't understand the issue.
`select` could be interrupted by a signal handler and the python implementation should throw an `InterruptedError`.
Is the issue related to https://www.python.org/dev/peps/pep-0475/ ?
> Changed in version 3.5: The function is now retried with a recomputed timeout when interrupted
> by a signal, except if the signal handler raises an exception (see PEP 475 for the rationale), 
> instead of raising InterruptedError.

An other solution could be to use https://docs.python.org/3/library/signal.html#signal.set_wakeup_fd ? (looks like signalfd without signalfd :) )
